name: Metrics
on:
  schedule: [{cron: "0 12 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Rooyca
          template: markdown
          filename: README.md
          markdown: https://raw.githubusercontent.com/Rooyca/Rooyca/main/.github/metrics.template.md
          config_output: markdown
          base: header, activity, community, repositories, metadata
          config_timezone: America/bogota
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_rss: yes
          plugin_rss_source: https://rooyca.github.io/es/index.xml
          plugin_rss_limit: 4
          plugin_achievements: yes
          plugin_achievements_display: compact
